name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm version from-git --no-git-tag-version -m "release v%s"
      - run: git status
      - run: git config --global user.name 'Juraj Chripko'
      - run: git config --global user.email 'juraj.chripko@goodrequest.com'
      - run: git add package.json package-lock.json
      - run: git status
      - run: git push origin HEAD:master
      - run: git status
      - run: npm i
      - run: npm run build
      - run: exit 1
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
