name: Build and run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Download codecov uploader
        run: curl https://uploader.codecov.io/verification.gpg | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
        run: curl -Os https://uploader.codecov.io/latest/linux/codecov
		run: curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
		run: curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
		run: gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
		run: shasum -a 256 -c codecov.SHA256SUM
		run: chmod +x codecov
		run: ./codecov -t ${CODECOV_TOKEN}


